# Generated by Django 5.0.6 on 2024-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='test', upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealtime',
            name='image',
            field=models.ImageField(default='test', upload_to='image'),
            preserve_default=False,
        ),
    ]
