# Generated by Django 5.0.6 on 2024-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_item_image_mealtime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtime',
            name='is_drink',
            field=models.BooleanField(default=False),
        ),
    ]
